use_frameworks!

platform :ios, '13.0'

target 'SkeletonTableRail_Example' do
  pod 'SkeletonTableRail', :path => '../'

  target 'SkeletonTableRail_Tests' do
    inherit! :search_paths

    
  end
end
